export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_RESET = "AUTH_RESET";

export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";

export const CLASSROOM_SUCCESS = "CLASSROOM_SUCCESS";
export const CLASSROOM_ADD_CREATED = "CLASSROOM_ADD_CREATED";

export const JOINED_CLASSROOM_SUCCESS = "JOINED_CLASSROOM_SUCCESS";
export const JOINED_CLASSROOM_ADD = "JOINED_CLASSROOM_ADD";

export const ACTION_START = "ACTION_START";
export const ACTION_SUCCESS = "ACTION_SUCCESS";
export const ACTION_ERROR = "ACTION_ERROR";
export const ACTION_RESET = "ACTION_RESET";
export const SET_CLASSROOM = "SET_ACTIVE_CLASS";
export const RESET_CLASSROOM = "RESET_ACTIVE_CLASS";

export const MATERIAL_SUCCESS = "MATERIAL_SUCCESS";
export const MATERIAL_ADD = "MATERIAL_ADD";
export const MATERIAL_DELETE = "MATERIAL_DELETE";

export const DISCUSSION_SUCCESS = "DISCUSSION_SUCCESS";
export const DISCUSSION_ADD = "DISCUSSION_ADD";
export const DISCUSSION_MARKED_SOLVED = "DISCUSSION_MARKED_SOLVED";

export const ANSWER_SUCCESS = "QUESTION_SUCCESS";
export const ANSWER_ADD = "QUESTION_ADD";

export const ASSIGNMENT_SUCCESS = "ASSIGNMENTS_SUCCESS";
export const ASSIGNMENT_ADD = "ASSIGNMENT_ADD";
export const ASSIGNMENT_SUBMITTED = "ASSIGNMENT_SUBMITTED";

export const SUBMISSION_SUCCESS = "SUBMISSION_SUCCESS";

export const STUDENT_SUCCESS = "STUDENT_SUCCESS";

export const OPTION_START = "OPTION_START";
export const OPTION_ERROR = "OPTION_ERROR";
export const OPTION_SUCCESS = "OPTION_SUCCESS";
